"""Initial Migration

Revision ID: 5e159f5dbfcc
Revises: 172cfbb92625
Create Date: 2019-04-22 19:56:23.720001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e159f5dbfcc'
down_revision = '172cfbb92625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=1000), nullable=True))
    op.drop_column('comments', 'feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('feedback', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
